### ISSUE TITLE
Need debug printout of the data container being read by ExtData

### ISSUE THREAD

**Issue by yantosca** [geoschem/MAPL#30]
Currently, the name of the data container being read from ExtData is not visible in the debug output.  This makes it difficult to isolate netCDF files that are incompatible with GCHP, as the run will just stop wiithout providing any information.

**Comment by lizziel** [comment]
To be clear, there is traceback printed by MAPL if there is an error reading the line in `ExtData.rc`. This traceback can be used to determine which info is being read in the line, e.g. regridding method, temporal read frequency, or filename. But no information is given about which line in the file was being read since the MAPL code is done in a loop over all `ExtData.rc` entries.

**Comment by yantosca** [comment]
@lizziel: Thanks for the clarification!
